### ISSUE TITLE
Modification of .gitignore

### ISSUE THREAD

**Issue by crbassett** [ianmwelch/designstandards#2]
I modified the .gitignore file to include macOS stuff and a standard .gitignore from GitHub for Jekyll purposes, which ignores the `_site` directory. This is nice because every time you make a minor change to a file on the site you don't also upload an entirely new version of the website (if you've been rebuilding locally).

The `_site` folder doesn't have to be in the repo when deploying to AWS Amplify. Does it need to be there for the current hosting solution?

**Comment by ianmwelch** [comment]
I think it does. I'm using Capistrano with DigitalOcean and I have to build the site locally and push to Github where the _site directory is then used by DigitalOcean.

**Comment by crbassett** [comment]
Understood. I think it'd be best to deploy this to AWS pretty soon instead. The cost will almost certainly be lower and we'll probably have access to some nice development features, like being able to have multiple branches with live, web-based instances. I'll file that as a task here on GitHub.
