### ISSUE TITLE
Syncing local development environments

### ISSUE THREAD

**Issue by crbassett** [ianmwelch/designstandards#3]
I'm trying to build the website locally on my Mac and when I run the following command:

`bundle exec jekyll serve --livereload`

I get the following error:

`Could not find rake-12.3.0 in any of the sources`

I'm not sure what's asking for this. The other Jekyll sites I've developed so far don't give me this error. Do you know what specifically this is for? Is it required? If not, can we cut it out?

**Comment by ianmwelch** [comment]
I just use `jekyll serve` on my Mac locally. I think that comes from Capistrano which I use to deploy to DigitalOcean. Not sure if it's required.
